//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bookingTable()
        {
            this.passengerTables = new HashSet<passengerTable>();
        }
    
        public string bookingId { get; set; }
        public string scheduleId { get; set; }
        public System.DateTime bookedDate { get; set; }
        public System.TimeSpan bookedTime { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<passengerTable> passengerTables { get; set; }
        public virtual flightSchedule flightSchedule { get; set; }
    }
}
