//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlightProjectEntities2 : DbContext
    {
        public FlightProjectEntities2()
            : base("name=FlightProjectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bookingTable> bookingTables { get; set; }
        public virtual DbSet<cityTable> cityTables { get; set; }
        public virtual DbSet<flightSchedule> flightSchedules { get; set; }
        public virtual DbSet<flightTable> flightTables { get; set; }
        public virtual DbSet<passengerTable> passengerTables { get; set; }
        public virtual DbSet<userTable> userTables { get; set; }
    }
}
